import { test } from 'node:test';
import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { generate, matches, validate, type Profile } from '../src/model';
import { pageAction } from '../src/page';
const p: Profile = { version: 1, id: 'demo', name: 'Demo', origin: 'https://uat.example.test', route: '/orders/new', descendants: true, scope: '#order', mappings: {firstName:'#first',lastName:'#last',accession:'#acc',mrn:'#mrn'},consents:[{label:'Care',group:'#care',yes:'input[value=yes]'}],prefix:'Test',maxLength:30,overwrite:false };
function fixture() {
  const dom = new JSDOM(`<form id="order"><input id="first"><input id="last"><input id="acc"><input id="mrn"><fieldset id="care"><input type="radio" name="care" value="yes"><input type="radio" name="care" value="no" checked></fieldset><fieldset id="other"><input type="radio" name="other" value="yes"><input type="radio" name="other" value="no" checked></fieldset></form>`, {url:p.origin+p.route});
  const w = dom.window;
  for (const key of ['document','location','HTMLInputElement','HTMLElement','Event','getComputedStyle'] as const) Object.defineProperty(globalThis,key,{value: key==='getComputedStyle'?w.getComputedStyle.bind(w):w[key],configurable:true});
  w.Element.prototype.getClientRects = function(){ return [{width:10,height:10}] as unknown as DOMRectList; };
  return w.document;
}
test('route matching uses origin and slash boundaries', () => { assert(matches(p.origin+'/orders/new/step',p)); assert(!matches(p.origin+'/orders/new-admin',p)); assert(!matches('https://uat.example.test.evil/orders/new',p)); assert(!matches(p.origin+'/orders/new/step',{...p,descendants:false})); });
test('ticket string produces stable names and paired fresh numeric IDs', () => { const a=generate('QA-00123',p), b=generate('QA-00123',p); assert.equal(a.ticket,'QA-00123'); assert.equal(a.firstName,b.firstName); assert.equal(a.lastName,b.lastName); assert.match(a.firstName,/^[A-Za-z]+$/); assert.equal(a.accession.slice(4),a.mrn.slice(4)); assert.match(a.accession,/^ACC-00123\d+$/); assert.notEqual(a.accession,b.accession); assert.throws(()=>generate(' ',p)); validate(p); });
test('fills names and paired references, isolates consent, repeats safely', async () => { const d=fixture(),record=generate('QA-42',p); const r=await pageAction({action:'fill',profile:p,record}); assert.equal(r.outcomes.filter(o=>o.status==='filled').length,5); assert.equal((d.querySelector('#first') as HTMLInputElement).value,record.firstName); assert((d.querySelector('#care input[value=yes]') as HTMLInputElement).checked); assert((d.querySelector('#other input[value=no]') as HTMLInputElement).checked); const again=await pageAction({action:'fill',profile:p,record}); assert(again.outcomes.every(o=>o.status==='unchanged')); });
test('preserves typed fields while setting consent; explicit overwrite replaces', async () => { const d=fixture(), first=d.querySelector('#first') as HTMLInputElement; first.value='Existing'; const record=generate('007',p); await pageAction({action:'fill',profile:p,record}); assert.equal(first.value,'Existing'); assert((d.querySelector('#care input[value=yes]') as HTMLInputElement).checked); await pageAction({action:'fill',profile:p,record,overwrite:true}); assert.equal(first.value,record.firstName); });
test('ambiguous, alias, disabled and invalid constraints are skipped', async () => { const d=fixture(); d.querySelector('#last')!.setAttribute('class','duplicate'); d.querySelector('#first')!.setAttribute('class','duplicate'); d.querySelector('#acc')!.setAttribute('maxlength','5'); d.querySelector('#care input[value=yes]')!.setAttribute('disabled',''); const r=await pageAction({action:'fill',profile:{...p,mappings:{...p.mappings,firstName:'.duplicate'}},record:generate('A',p)}); assert.equal(r.outcomes.find(o=>o.field==='firstName')!.status,'skipped'); assert.equal(r.outcomes.find(o=>o.field==='accession')!.status,'skipped'); assert.equal(r.outcomes.find(o=>o.field==='Care')!.status,'skipped'); const alias=await pageAction({action:'fill',profile:{...p,mappings:{...p.mappings,lastName:'#first'}},record:generate('A',p)}); assert(alias.outcomes.filter(o=>['firstName','lastName'].includes(o.field)).every(o=>o.status==='skipped')); });
test('scope mismatch never mutates', async () => { const d=fixture(); const r=await pageAction({action:'fill',profile:{...p,route:'/elsewhere'},record:generate('A',p)}); assert.equal(r.outcomes[0].status,'failed'); assert.equal((d.querySelector('#first') as HTMLInputElement).value,''); });
test('controlled replacement persists; deferred rejection is failed', async () => { const d=fixture(); let model=''; d.querySelector('#first')!.addEventListener('input',e=>{const input=e.target as HTMLInputElement;model=input.value;const replacement=input.cloneNode() as HTMLInputElement;replacement.value=model;input.replaceWith(replacement)}); const record=generate('A',p); const accepted=await pageAction({action:'fill',profile:p,record}); assert.equal(accepted.outcomes[0].status,'filled'); assert.equal(model,record.firstName); d.querySelector('#first')!.addEventListener('input',()=>setTimeout(()=>{(d.querySelector('#first') as HTMLInputElement).value='Rejected'},50)); const rejected=await pageAction({action:'fill',profile:p,record:generate('B',p),overwrite:true}); assert.equal(rejected.outcomes[0].status,'failed'); });
test('concurrent fills are rejected and missing controls finish within budget',async()=>{fixture();const req={action:'fill' as const,profile:{...p,mappings:{...p.mappings,mrn:'#missing'}},record:generate('A',p)};const first=pageAction(req);const second=await pageAction(req);assert.match(second.outcomes[0].reason,/already running/);const done=await first;assert.equal(done.outcomes.find(o=>o.field==='mrn')!.status,'skipped');assert(done.elapsed<5000)});
